### ISSUE TITLE
Cursor resets to start of file

### ISSUE THREAD

**Issue by irvnriir** [patmood/rich-markdown-editor-vsc#1]
Each time when any character is written .

**Comment by patmood** [comment]
Do you have any formatters enabled for markdown? I noticed this happens with prettier

**Comment by irvnriir** [comment]
I think i tried with other extensions disabled . i don't have any formatters installed, as far i know .

**Comment by ArthurBZhou** [comment]
The editor is great！！！but i recreated this bug, and i tried with other extensions disabled too.

**Comment by lenielluzardo** [comment]
Hello, I have the same bug. Everytime I write something the cursor goes back to start. Did you find any solution?

**Comment by patmood** [comment]
This happens when the underlying file contents change. Eg a formatter or you save the file in another tab/window

**Comment by ChristopherHaws** [comment]
@patmood I set the following settings in my workspace, and I still have this issue. Any ideas?
```
{
    "[markdown]": {
        "editor.defaultFormatter": null,
        "editor.formatOnSave": false,
        "editor.formatOnType": false,
        "editor.formatOnPaste": false
    },
}
```

**Comment by patmood** [comment]
Which VSCode version and operating system are people using that have this issue? I know it's a big problem but I haven't been able to reproduce outside of auto-formatting extensions.

**Comment by ChristopherHaws** [comment]
Here are my stats:
```
Version: 1.75.1 (system setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621 (Windows 11 Pro for Workstations)
Sandboxed: No
```

Really hope we can get this fixed, this plugin looks amazing! ^_^

**Comment by ChristopherHaws** [comment]
I just created a brand new, empty profile in VS Code, installed only this extension in it, and the issue happens.

Here is an export of the profile:
[rich-markdown-editor-issue.zip](https://github.com/patmood/rich-markdown-editor-vsc/files/10876024/rich-markdown-editor-issue.zip)

**Comment by Bullish-Design** [comment]
Any updates on this?

I followed the same steps, had the same issues as @ChristopherHaws

**Comment by patmood** [comment]
Thanks @pelece for finding and fixing this windows bug!
