### ISSUE TITLE
Cursor bug

### ISSUE THREAD

**Issue by FelipeMarra** [patmood/rich-markdown-editor-vsc#10]
Cursor keeps jumping to the first line as soon as one start typing.
![READMEmd   joint intent detection and slot filling   Visual Studio Code 2023 09 21 20 06 51](https://github.com/patmood/rich-markdown-editor-vsc/assets/89817439/2c137887-9e04-4ac9-b33e-3b9cf2eabcca)

**Comment by kosirm** [comment]
Same here. It makes it completely unusable. But it looks promising. Hopefully, this will be solved.

**Comment by kryptot7** [comment]
I have this issue as well. I'm running 64-bit Windows 11. I checked to make sure all the settings listed in issue #1 were off, and they were. Sad because otherwise this looks like an extremely promising plugin.

**Comment by patmood** [comment]
Thanks @pelece for finding and fixing this windows bug!
